/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daily.attandance.system;

import java.awt.HeadlessException;
import java.lang.Thread.State;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class firstyear extends javax.swing.JFrame {

    /**
     * Creates new form firstyear
     */
    public firstyear() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        roll = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        enroll = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        l_number = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        l_enroll = new javax.swing.JLabel();
        l_mobile = new javax.swing.JLabel();
        l_address = new javax.swing.JLabel();
        l_mail = new javax.swing.JLabel();
        l_course = new javax.swing.JLabel();
        course = new javax.swing.JTextField();
        l_c = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 610, 85, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daily/attandance/back.png"))); // NOI18N
        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 610, 140, 33);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("First Year");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(249, 60, 206, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Roll Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(15, 190, 108, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Students Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 250, 130, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Enrollment No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(15, 323, 125, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Mobile No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(15, 378, 110, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(290, 610, 84, 37);

        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        roll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rollKeyReleased(evt);
            }
        });
        jPanel1.add(roll);
        roll.setBounds(158, 192, 156, 26);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(160, 250, 153, 26);

        enroll.setText(" ");
        enroll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                enrollKeyReleased(evt);
            }
        });
        jPanel1.add(enroll);
        enroll.setBounds(161, 320, 151, 26);

        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileKeyReleased(evt);
            }
        });
        jPanel1.add(mobile);
        mobile.setBounds(161, 375, 151, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Daily Attendance System");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(141, 0, 347, 51);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 255));
        jLabel9.setText("Students Information ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 112, 265, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("E-mail");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(15, 484, 90, 20);

        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
        });
        jPanel1.add(mail);
        mail.setBounds(161, 481, 151, 26);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Course");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(15, 536, 78, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Address");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(15, 438, 90, 20);

        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressKeyReleased(evt);
            }
        });
        jPanel1.add(address);
        address.setBounds(161, 435, 151, 26);

        l_number.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        l_number.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l_number);
        l_number.setBounds(350, 190, 200, 20);

        l_name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        l_name.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l_name);
        l_name.setBounds(340, 250, 178, 30);

        l_enroll.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        l_enroll.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l_enroll);
        l_enroll.setBounds(340, 320, 220, 30);

        l_mobile.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        l_mobile.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l_mobile);
        l_mobile.setBounds(340, 370, 200, 30);

        l_address.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        l_address.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l_address);
        l_address.setBounds(340, 430, 240, 30);

        l_mail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        l_mail.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l_mail);
        l_mail.setBounds(350, 480, 260, 30);

        l_course.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        l_course.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l_course);
        l_course.setBounds(386, 497, 250, 40);

        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        course.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                courseKeyReleased(evt);
            }
        });
        jPanel1.add(course);
        course.setBounds(161, 533, 151, 26);

        l_c.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        l_c.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(l_c);
        l_c.setBounds(360, 530, 210, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daily/j4.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, -40, 620, 480);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/daily/j4.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 270, 620, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new page2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new firstyearattandance().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("empty-statement")
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
     
         if(roll.getText().trim().isEmpty()&& name.getText().trim().isEmpty() && enroll.getText().trim().isEmpty()&& mobile.getText().trim().isEmpty()&& address.getText().trim().isEmpty()&& mail.getText().trim().isEmpty()&& course.getText().trim().isEmpty())
        {
             l_number.setText("Please enter rollno");
            l_name.setText("please enter name");
            l_enroll.setText("Please enter enrollmentno");
            l_mobile.setText("please enter mobileno");
            l_address.setText("Please enter address");
            l_mail.setText("Please enter e-mail");
            l_c.setText("Please enter course");
        }
             else if(roll.getText().trim().isEmpty())
        {
           l_number.setText("Please enter rollno");
        }
             else if(name.getText().trim().isEmpty())
        {
           l_name.setText("please enter name");
        }
             else if(enroll.getText().trim().isEmpty())
        {
          l_enroll.setText("Please enter enrollmentno");
        }
             else if(mobile.getText().trim().isEmpty())
        {
          l_mobile.setText("Please enter enrollmentno");
        }
             else if(address.getText().trim().isEmpty())
        {
          l_address.setText("Please enter address");
        }
             else if(mail.getText().trim().isEmpty())
        {
         l_mail.setText("Please enter e-mail");
        }
             else if(course.getText().trim().isEmpty())
        {
         l_c.setText("Please enter course");
        }                 
             else
        {
              
try{  
                        //step1 l  oad the driver class  
                        Class.forName("oracle.jdbc.driver.OracleDriver");  

                        //step2 create  the connection object  
                        Connection con=DriverManager.getConnection(  
                        "jdbc:oracle:thin:@localhost:1521:xe","system","system");  

                        //step3 create the statement object 
                        String sql ="insert into first values(?,?,?,?,?,?,?)";
                        PreparedStatement pstmt =con.prepareStatement(sql);
                        pstmt.setString(1,roll.getText());
                        pstmt.setString(2,name.getText());
                        pstmt.setString(3,enroll.getText());
                        pstmt.setString(4,mobile.getText());
                        pstmt.setString(5,address.getText());
                        pstmt.setString(6,mail.getText());
                        pstmt.setString(7,course.getText());
                        
                        pstmt.executeUpdate();
                         JOptionPane.showMessageDialog(null," Data Inserted Successfully");

                        //step5 close the connection object  
                        con.close();  

                        }catch(ClassNotFoundException | SQLException | HeadlessException e){ JOptionPane.showMessageDialog(null,"");;}  

        }      
        
    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void rollKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollKeyReleased
        // TODO add your handling code here:
        l_number.setText("");
    }//GEN-LAST:event_rollKeyReleased

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
        l_name.setText("");
    }//GEN-LAST:event_nameKeyReleased

    private void enrollKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrollKeyReleased
        // TODO add your handling code here:
        l_enroll.setText("");
    }//GEN-LAST:event_enrollKeyReleased

    private void mobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyReleased
        // TODO add your handling code here:
        l_mobile.setText("");
    }//GEN-LAST:event_mobileKeyReleased

    private void addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyReleased
        // TODO add your handling code here:
        l_address.setText("");
    }//GEN-LAST:event_addressKeyReleased

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyReleased
        // TODO add your handling code here:
        l_mail.setText("");
    }//GEN-LAST:event_mailKeyReleased

    private void courseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseKeyReleased
        // TODO add your handling code here:
        l_c.setText("");
    }//GEN-LAST:event_courseKeyReleased

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstyear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstyear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstyear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstyear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstyear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField course;
    private javax.swing.JTextField enroll;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_address;
    private javax.swing.JLabel l_c;
    private javax.swing.JLabel l_course;
    private javax.swing.JLabel l_enroll;
    private javax.swing.JLabel l_mail;
    private javax.swing.JLabel l_mobile;
    private javax.swing.JLabel l_name;
    private javax.swing.JLabel l_number;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField roll;
    // End of variables declaration//GEN-END:variables
}
